<script lang="ts">
	import EscapeRoomGame from '$lib/EscapeRoomGame.svelte';
</script>

<div class="min-h-dvh flex flex-col items-center px-5 sm:px-8 py-10 sm:py-14">
	<div class="w-full max-w-5xl flex flex-col gap-6">

		<!-- Header -->
		<header class="text-center flex flex-col items-center gap-2 mb-4">
			<div class="relative">
				<div class="absolute inset-0 blur-2xl opacity-30 bg-[#7c6af7] rounded-full scale-150"></div>
				<h1 class="relative font-display text-5xl sm:text-6xl font-bold tracking-tight">
					<span class="text-white">ai</span><span class="text-transparent bg-clip-text bg-gradient-to-r from-[#7c6af7] to-[#c084fc]">talk</span>
				</h1>
			</div>
			<p class="text-sm text-[--color-muted] tracking-wide">an escape room generated by AI</p>
			<!-- Nav -->
			<div class="flex items-center gap-1 mt-1 bg-[--color-panel] border border-[--color-border] rounded-xl p-1">
				<a href="/" class="text-[11px] font-semibold uppercase tracking-widest px-3 py-1.5 rounded-lg text-[--color-muted] hover:text-white transition-colors">⚔ Debate</a>
				<span class="text-[11px] font-semibold uppercase tracking-widest px-3 py-1.5 rounded-lg bg-[--color-accent]/10 text-[--color-accent]">🗝️ Escape Room</span>
				<a href="/story" class="text-[11px] font-semibold uppercase tracking-widest px-3 py-1.5 rounded-lg text-[--color-muted] hover:text-white transition-colors">📖 Story</a>
			</div>
		</header>

		<!-- Escape Room Content -->
		<EscapeRoomGame />

	</div>
</div>