<script lang="ts">
  import Nav from "$lib/Nav.svelte";
  import EscapeRoomGame from "$lib/EscapeRoomGame.svelte";
</script>

<div class="w-full max-w-5xl flex flex-col gap-6">

  <!-- Header -->
  <header class="text-center flex flex-col items-center gap-2 mb-4">
    <div class="relative">
      <div class="absolute inset-0 blur-2xl opacity-30 bg-[#7c6af7] rounded-full scale-150"></div>
      <h1 class="relative font-display text-5xl sm:text-6xl font-bold tracking-tight">
        <span class="text-white">AI </span><span class="text-transparent bg-clip-text bg-gradient-to-r from-[#7c6af7] to-[#c084fc]">Escape Room</span>
      </h1>
    </div>
    <p class="text-sm text-[--color-muted] tracking-wide">an escape room generated by AI</p>
    <Nav />
  </header>

  <!-- Escape Room Content -->
  <EscapeRoomGame />

</div>